# Generated by Django 4.0.8 on 2022-12-18 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_alter_product_shoe_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="contact_name",
            field=models.CharField(
                help_text="Name of the provider's contact.",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z ]*$",
                        "Only alphabetic characters and spaces are allowed.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="contact_number",
            field=models.CharField(
                help_text="Phone number of the provider's contact.",
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]*$", "Only numeric characters are allowed."
                    ),
                    django.core.validators.MinLengthValidator(9),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="ruc",
            field=models.CharField(
                help_text="RUC of the provider.",
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(10|20|15|16|17)[0-9]{9}$",
                        "Invalid RUC. It must start with 10, 20, 15, 16, or 17 and be 11 numbers long.",
                    )
                ],
            ),
        ),
    ]
