# Generated by Django 4.0.8 on 2022-12-19 20:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("management", "0005_alter_storeroom_allocations"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp of the sale."
                    ),
                ),
                (
                    "full_sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price of the sale.",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.0, "The sale price cannot be negative."
                            )
                        ],
                    ),
                ),
                (
                    "point_of_sale",
                    models.ForeignKey(
                        help_text="Sale's point of sale.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.pointofsale",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User that performs the sale.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sale price of the product.",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.0, "The sale price cannot be negative."
                            )
                        ],
                    ),
                ),
                (
                    "number_of_units",
                    models.PositiveSmallIntegerField(help_text="Number of units."),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Related product.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        help_text="Related sale.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales.sale",
                    ),
                ),
            ],
        ),
    ]
