# Generated by Django 4.0.8 on 2022-12-19 23:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_alter_storeroom_allocations"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="full_sale_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total price of the sale.",
                max_digits=8,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.0, "The sale price cannot be negative."
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount.",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.0, "The sale price cannot be negative."
                            )
                        ],
                    ),
                ),
                (
                    "operation_code",
                    models.CharField(
                        blank=True,
                        help_text="Operation code related to the payment.",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "payment_type",
                    models.ForeignKey(
                        help_text="Payment type.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.paymenttype",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        help_text="Related sale.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales.sale",
                    ),
                ),
            ],
        ),
    ]
