# Generated by Django 4.0.8 on 2022-12-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_alter_sale_full_sale_price_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="pending_payment",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Pending payment of the sale.",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="full_sale_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total price of the sale.",
                max_digits=8,
            ),
        ),
    ]
