# Generated by Django 4.0.8 on 2022-11-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_owner",
            field=models.BooleanField(
                default=False, help_text="Whether this is an owner user."
            ),
        ),
    ]
