# Generated by Django 4.0.8 on 2022-12-18 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_is_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                help_text="User's full name.",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z ]*$",
                        "Only alphabetic characters and spaces are allowed.",
                    )
                ],
            ),
        ),
    ]
